events {}

http {
    server {
        listen 80;

        # Sub-domain của em 
        server_name nguyentrunghiieu.id.vn;

        # ── Phục vụ file tĩnh
        # location / trỏ root tới thư mục /myweb trong container
        location / {
            root /myweb;
            index index.html index.htm;
            try_files $uri $uri/ =404;
        }

        # ── Proxy tới Node-RED
        # "mynodered" là tên container, docker network tự resolve DNS
        location /nodered/ {
            proxy_pass http://mynodered:1880/;
            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        }
    }
}
