services:
  # ── Node-RED
  mynodered:
    image: nodered/node-red
    container_name: mynodered
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - ./nodered:/data
    deploy:
      resources:
        limits:
          memory: 512M

  # ── Nginx
  mynginx:
    image: nginx
    container_name: mynginx
    restart: always
    ports:
      - "80:80"
    volumes:
      # Mount thư mục ./myweb thành /myweb trong container
      - ./myweb:/myweb:ro
      # Mount file cấu hình nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mynodered
  mycloudflared:
    image: cloudflare/cloudflared:latest
    container_name: mycloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}
